### ISSUE TITLE
help

### ISSUE THREAD

**Issue by maiziheimei** [taiwotman/flasklogin_neo4j#1]
Hey, I found your project is very interesting ... I downloaded it and I have problems to run it ... 
  For example ...

'... user = db.graph.find_one('User', 'email', self.email)
AttributeError: 'Graph' object has no attribute 'find_one''

I see a 'User' node and Property Keys 'email' have been created but no values ... 

Can you help? Thanks!

**Comment by OAdesanya** [comment]
It might be due to the version. A similar issue has been raised on [Stackoverflow](https://stackoverflow.com/questions/52056004/py2neo-v4-attributeerror-graph-object-has-no-attribute-find-one). 
Also, set up the Neo4j graph database and have its server running at the backend.

**Comment by taiwotman** [comment]
It might be due to the version. A similar issue has been raised on Stackoverflow.
Also, set up the Neo4j graph database and have its server running at the backend.
