### ISSUE TITLE
'AttributeError: 'Graph' object has no attribute 'find_one''

### ISSUE THREAD

**Issue by maiziheimei** [taiwotman/flasklogin_neo4j#2]
I tried your project, but got error,

'AttributeError: 'Graph' object has no attribute 'find_one''

**Comment by josh-thurston** [comment]
https://stackoverflow.com/questions/52056004/py2neo-v4-attributeerror-graph-object-has-no-attribute-find-one

I ran into that issue also.  I ended up having to do everything in a different way.

**Comment by maiziheimei** [comment]
> https://stackoverflow.com/questions/52056004/py2neo-v4-attributeerror-graph-object-has-no-attribute-find-one
> 
> I ran into that issue also. I ended up having to do everything in a different way.

I found that post,... as you said you have ended up doing everything in a different way, ... do you mind providing a working version by sharing your own new GitHub project? ... 

Thanks for any help.

**Comment by taiwotman** [comment]
@maiziheimei if you have any issue, please be clear on your question by sharing a code sample and where the error occurred.

**Comment by maiziheimei** [comment]
sooo glad that  @taiwotman saw my problem. 

Neo4j is on and running with empty DB; app is running on localhost:5000; Since for the first time, I hit 'singup', then filled the 'name' and 'email', then here comes the error messages:

- from 'http://127.0.0.1:5000/signup', it shows 'Internal Server Error:    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'

- from neo4j db, I saw Node 'User', with Property keys 'email', 'name','username', but no actual values what I just filled

- from the terminal, I got,

> ' * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [15/Jul/2020 19:24:17] "GET / HTTP/1.1" 302 -
> 127.0.0.1 - - [15/Jul/2020 19:24:17] "GET /login HTTP/1.1" 200 -
> 127.0.0.1 - - [15/Jul/2020 19:24:18] "GET /static/dist/js/main.min.js HTTP/1.1" 200 -
> 127.0.0.1 - - [15/Jul/2020 19:24:18] "GET /static/dist/img/logo.png HTTP/1.1" 200 -
> 127.0.0.1 - - [15/Jul/2020 19:24:18] "GET /static/dist/img/backgroundimg2.jpeg HTTP/1.1" 200 -
> 127.0.0.1 - - [15/Jul/2020 19:24:18] "GET /static/dist/js/includes/jquery.min.js HTTP/1.1" 200 -
> 127.0.0.1 - - [15/Jul/2020 19:24:20] "GET /signup HTTP/1.1" 200 -
> [2020-07-15 19:24:45,836] ERROR in app: Exception on /signup [POST]
> Traceback (most recent call last):
>   File ".../python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File ".../python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File ".../lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File ".../lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "...//lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "...//lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File ".../application/auth.py", line 97, in signup_page
>     existing_user = user.find()
>   File ".../application/models.py", line 28, in find
>     user = db.graph.find_one('User', 'email', self.email)
> AttributeError: 'Graph' object has no attribute 'find_one'
> 127.0.0.1 - - [15/Jul/2020 19:24:45] "POST /signup HTTP/1.1" 500 -
> 127.0.0.1 - - [15/Jul/2020 19:24:46] "GET /favicon.ico HTTP/1.1" 404 -"


Really appreciate your help and I am completely new to this kind of app. THANK YOU.

**Comment by taiwotman** [comment]
`find_one` is deprecated.  Either downgrade to  `Py2neo 2.0.9 ` or try the following code lines.

```
from py2neo import NodeMatcher

matcher = NodeMatcher(db.graph)
matcher.match("User", email=self.email).first()
```

Specifically in the _model_ python script
```
def find(self):
        user = matcher.match("User", email = self.email).first()
        return user

def get_id(self):
        query = 'match (n:User) where n.email = {email} return ID(n)'

        user = matcher.match("User", email = self.email).first()
        id = db.graph.run(query, parameters = {'email': user['email']}).evaluate()

        return id
```

**Comment by josh-thurston** [comment]
I wrote this an entirely different way.  If you want more ideas check out https://github.com/josh-thurston/FlaskNeo4jStarter

**Comment by maiziheimei** [comment]
> from py2neo import NodeMatcher
> 
> matcher = NodeMatcher(db.graph)

Thanks, @taiwotman , I put these code into the 'model.py', I got the error from the same place,

**Comment by maiziheimei** [comment]
> `find_one` is deprecated. Either downgrade to `Py2neo 2.0.9 ` or try the following code lines.
> 
> ```
> from py2neo import NodeMatcher
> 
> matcher = NodeMatcher(db.graph)
> matcher.match("User", email=self.email).first()
> ```
> 
> Specifically in the _model_ python script
> 
> ```
> def find(self):
>         user = matcher.match("User", email = self.email).first()
>         return user
> 
> def get_id(self):
>         query = 'match (n:User) where n.email = {email} return ID(n)'
> 
>         user = matcher.match("User", email = self.email).first()
>         id = db.graph.run(query, parameters = {'email': user['email']}).evaluate()
> 
>         return id
> ```

Thanks, @taiwotman , I put these code into the 'model.py'.

In case let you know what is going on, .... I got the error from the same place,

> '127.0.0.1 - - [15/Jul/2020 21:03:44] "GET /signup HTTP/1.1" 200 -
> [2020-07-15 21:04:16,297] ERROR in app: Exception on /signup [POST]

and

> '
>     raise GraphError.hydrate(metadata)
> py2neo.database.ClientError: SyntaxError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 32 (offset: 31))
> "MATCH (_:User) WHERE _.email = {1} RETURN _"
>                                 ^
> 127.0.0.1 - - [15/Jul/2020 21:04:16] "POST /signup HTTP/1.1" 500 
> '

very tried, I will debug it tomorrow, ... hopefully eventually with all your help, this project can work from my pc. THANKS.

**Comment by maiziheimei** [comment]
hey,  Good Morning @taiwotman, your project is very interesting,  I want to try it out locally. Now I have new problems, wish you could help me.

First, the following is working for me,

>    def find(self):
>         user = matcher.match("User", email=self.email).first()
>         return user
> 
>     def get_id(self):
>         query = 'match (n:User) where n.email="{vemail}" return ID(n)'
>         user = matcher.match("User", email=self.email).first()
>         id = db.graph.run(query, vemail=user['email']).evaluate()
>         return id
> 
>     def set_lastlogin(self):
>         query = 'MATCH (p:User) SET p.last_login="{v_last_login}" return p'
>         db.graph.run(query, v_last_login=self.last_login)

Now I have two problems,

1. after signup, I tried to log in, inside neo4j, the 'last_login' is set as 

> ''"last_login": "{v_last_login}",  

2. it never goes to 'dash_board', instead it goes to 'login' page

> ' return redirect(next or url_for('main_bp.dashboard'))', line 49 of 'auth.py'
or 
              
>   return redirect(url_for('main_bp.dashboard')), line 102 of 'auth.py'

Thank you.

**Comment by taiwotman** [comment]
Moved _deleted comment_ to new issue: [_Redirect to dashboard page_](https://github.com/taiwotman/flasklogin_neo4j/issues/3).
