### ISSUE TITLE
Redirect to dashboard page

### ISSUE THREAD

**Issue by maiziheimei** [taiwotman/flasklogin_neo4j#3]
hey,  Good Morning @taiwotman, your project is very interesting,  I want to try it out locally. Now I have new problems, wish you could help me.

First, the following is working for me,

>      def find(self):
>         user = matcher.match("User", email=self.email).first()
>         return user
> 
>     def get_id(self):
>         query = 'match (n:User) where n.email="{vemail}" return ID(n)'
>         user = matcher.match("User", email=self.email).first()
>         id = db.graph.run(query, vemail=user['email']).evaluate()
>         return id
> 
>     def set_lastlogin(self):
>         query = 'MATCH (p:User) SET p.last_login="{v_last_login}" return p'
>         db.graph.run(query, v_last_login=self.last_login)

Now I have two problems,

1. after signup, I tried to log in, inside neo4j, the 'last_login' is set as 

> ''"last_login": "{v_last_login}",  

2. it never goes to 'dash_board', instead it goes to 'login' page

> ' return redirect(next or url_for('main_bp.dashboard'))', line 49 of 'auth.py'
or 
              
>   return redirect(url_for('main_bp.dashboard')), line 102 of 'auth.py'

Thank you.

**Comment by taiwotman** [comment]
Nice. I am glad your login is working. The dashboard will only show if data  is added. 

See **Assumption:** 
_For test purpose, the sentiment analytics dashboard is provided without the data. You will need to modify the source code to fit your use-case._

**Comment by maiziheimei** [comment]
Dear @taiwotman Thanks for the advice and for your use-case, do you have test data?

Right now the problem was and is, the redirect is not working after logged in, it can not redirect to 'main_bp.dashboard'.

If I copy all the code from 'routes.py' to 'auth.py' and created a path as 'auth.bp_dashboard'', then it can direct to 'auth.bp_dashboard'.  

Thank you very much!
